#!/bin/zsh

function cloneOrUpdate () {
  URL="/$1"
  BUNDLE_FOLDER=$2
  clone_folder_name=$3
  if [ -z $clone_folder_name ]
  then
    clone_folder_name="$2/${URL##/*/}"
    echo $clone_folder_name
  else
    clone_folder_name="$2/$3"
  fi

  if [ -d $clone_folder_name/.git ]
  then
#    cd $clone_folder_name
    echo "pulling $clone_folder_name"
    git -C $clone_folder_name pull
  else
    echo "cloning new projet $1 into $clone_folder_name"
    git clone $1 $clone_folder_name
  fi

}

BUNDLE_PATH=~/.vim/bundle


WITH_LINKS="false"
while getopts ":wi" opt; do
  case $opt in
    w)
      WITH_LINKS="true" 
      ;;
    i)
      WITH_INSTALL="true" 
      ;;
  esac
done


#PLUGINS
mkdir -p ~/.vim/
mkdir -p ~/.zsh/

if [[ $WITH_INSTALL == "true" ]]
then
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -  
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

  sudo apt-get update
  sudo apt-get install -y vim-nox zsh git tmux google-chrome-stable 
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
  chsh -s /bin/zsh

  #docker
  sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker2.list'
  sudo apt-get update
  sudo apt-get purge lxc-docker
  apt-cache policy docker-engine
  sudo apt-get install -y linux-image-extra-$(uname -r)
  sudo apt-get install -y docker-engine
  sudo groupadd docker
  sudo usermod -aG docker $(id -un)
  exit 0
fi

if [[ $WITH_LINKS == "true" ]]
then
  echo "updating dependencies"
  mkdir -p ~/.vim/autoload/
  mkdir -p ~/.vim/bundle/
  cloneOrUpdate https://github.com/tpope/vim-pathogen.git ~/.vim pathogen
  ln -fs ~/.vim/pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim
  cloneOrUpdate https://github.com/tpope/vim-surround.git $BUNDLE_PATH vim-surround
  cloneOrUpdate https://github.com/godlygeek/csapprox.git $BUNDLE_PATH csapprox
  cloneOrUpdate https://github.com/fatih/vim-go.git $BUNDLE_PATH vim-go 
  cloneOrUpdate https://github.com/scrooloose/nerdtree.git $BUNDLE_PATH nerdtree
  cloneOrUpdate https://github.com/scrooloose/nerdcommenter.git $BUNDLE_PATH nerdcommenter
  cloneOrUpdate https://github.com/kchmck/vim-coffee-script.git $BUNDLE_PATH vim-coffee-script
  cloneOrUpdate git://github.com/digitaltoad/vim-jade.git $BUNDLE_PATH vim-jade
  cloneOrUpdate https://github.com/genoma/vim-less.git $BUNDLE_PATH vim-less
  cloneOrUpdate https://github.com/Shougo/neocomplete.vim.git $BUNDLE_PATH neocomplete.vim
  cloneOrUpdate https://github.com/szw/vim-ctrlspace.git $BUNDLE_PATH vim-ctrlspace
  cloneOrUpdate https://github.com/rking/ag.vim $BUNDLE_PATH ag
  cloneOrUpdate https://github.com/plasticboy/vim-markdown.git $BUNDLE_PATH vim-markdown
  cloneOrUpdate https://github.com/klen/python-mode $BUNDLE_PATH python-mode
  cloneOrUpdate https://github.com/lukerandall/haskellmode-vim.git $BUNDLE_PATH haskellmode-vim
  cloneOrUpdate https://github.com/scrooloose/syntastic.git $BUNDLE_PATH syntastic
  cloneOrUpdate https://github.com/majutsushi/tagbar $BUNDLE_PATH tagbar
  cloneOrUpdate https://github.com/elixir-lang/vim-elixir.git $BUNDLE_PATH vim-elixir
  cloneOrUpdate https://github.com/lambdatoast/elm.vim.git $BUNDLE_PATH elm.vim 
  cloneOrUpdate https://github.com/ekalinin/Dockerfile.vim.git $BUNDLE_PATH Dockerfile.vim

  cloneOrUpdate https://github.com/jelera/vim-javascript-syntax.git $BUNDLE_PATH vim-javascript-syntax
  cloneOrUpdate https://github.com/pangloss/vim-javascript.git $BUNDLE_PATH vim-javascript
  cloneOrUpdate https://github.com/nathanaelkane/vim-indent-guides $BUNDLE_PATH vim-indent
  
  cloneOrUpdate https://github.com/pearofducks/ansible-vim $BUNDLE_PATH ansible-vim
fi

#vimrc
rm -Rf ~/.vim/vimrc
ln -fs $PWD/vim ~/.vim/vimrc

#colors
rm -Rf ~/.vim/colors
ln -fs $PWD/vim/colors ~/.vim/colors

ln -fs ~/.vim/vimrc/vimrc ~/.vimrc
ln -fs $PWD/tmux/tmux-session ~/tmux-session
ln -fs $PWD/tmux/tmux.conf ~/.tmux.conf

#zsh
ln -fs $PWD/zsh/zshrc ~/.zshrc
ln -fs $PWD/zsh/completions ~/.zsh/completions

if [[ -d $ZSH/custom ]]
then
  mv $ZSH/custom $ZSH/custom_before_install
fi

if [[ -L $ZSH/custom ]]
then
  rm $ZSH/custom
fi
ln -fs $PWD/zsh/custom $ZSH/custom

