#!/bin/bash
SESSION=ide-session

tmux has-session -t $SESSION 
AllreadyExists=$?
echo $AllreadyExists

if [[ $AllreadyExists -eq 0 ]] 
then
    tmux -2 attach-session -d -t $SESSION
    exit 0
fi

tmux -2 new-session -d -s $SESSION

# Setup a window for tailing log files
tmux new-window -t $SESSION:1 -n 'Shells'
tmux split-window -h
tmux select-pane -t 0
tmux send-keys "echo 'pane1'" C-m
tmux select-pane -t 1
tmux send-keys "echo 'pane2'" C-m
tmux split-window -v
tmux resize-pane -D 5
tmux send-keys "htop" C-m
tmux select-pane -t 0
tmux split-window -v
tmux new-window -t $SESSION:2 -n 'Vim' 'vim'

# Set default window
tmux select-window -t $SESSION:1

# Attach to session
tmux -2 attach-session -t $SESSION

