#!/bin/bash

PROFILES="
HOME
SGDIR
GO
JHIPSTER
TROMBI
"

usage(){
  echo "only 1 argument needed as profile name"
  echo "available profiles are : $PROFILES"
}

nb_argument=$#

if [[ nb_argument -gt 1 ]]
then
  usage
  exit 1
fi

PROFILE=$1

echo $PROFILE

SESSION="ide-session-$1"

echo "creating tmux session $SESSION"

tmux has-session -t $SESSION
AllreadyExists=$?

if [[ $AllreadyExists -eq 0 ]] 
then
  echo "tmux session found, attaching to it"
  tmux -2 attach-session -d -t $SESSION
  exit 0
fi

tmux -2 new-session -d -s $SESSION

# Setup a window for tailing log files
#tmux new-window -t $SESSION:1 -n 'Shells'
tmux split-window -h
tmux select-pane -t 0
tmux select-pane -t 1
tmux split-window -v
tmux split-window -v
tmux split-window -v
tmux send-keys "htop" C-m
tmux select-pane -t 0
tmux split-window -v
tmux new-window -t $SESSION:2 -n 'Vim' 
tmux split-window -h
tmux split-window -v
tmux resize-pane -t 1 -R 15 # Set default window
tmux select-pane -t 0
tmux send-keys "cd ~/Projects && nvim" C-m
tmux select-window -t $SESSION:1

if [[ "$PROFILE" == "popartisan" || "$PROFILE" == "pop" || "$PROFILE" == "POPARTISAN" || "$PROFILE" == "POP" ]]
then
  tmux select-window -t $SESSION:1
  tmux select-pane -t 2
  tmux send-keys "" C-m
  tmux select-window -t $SESSION:2
  tmux select-pane -t 0
  tmux send-keys "" C-m
  tmux select-pane -t 1
  tmux send-keys "" C-m
  tmux select-pane -t 2
  tmux send-keys "" C-m
elif [[ "$PROFILE" == "trombi" || "$PROFILE" == "TROMBI" ]]
then
  tmux select-window -t $SESSION:1
  tmux select-pane -t 2
  tmux send-keys "g trombi" C-m
  tmux select-window -t $SESSION:2
  tmux rename-window -t $SESSION:2 'Elixir'
  tmux select-pane -t 0
  tmux send-keys "g trombi && nvim" C-m
  tmux select-pane -t 1
  tmux send-keys "g trombi" C-m
  tmux select-pane -t 2
  tmux send-keys "g trombi" C-m
  tmux new-window -t $SESSION:3 -n 'Vuejs' 
  tmux split-window -h
  tmux split-window -v
  tmux select-pane -t 0
  tmux send-keys "g trombi && nvim" C-m
  tmux resize-pane -t 1 -x 90 # Set default window
  tmux select-pane -t 1
  tmux send-keys "g trombi" C-m
  tmux select-pane -t 2
  tmux send-keys "g trombi" C-m
  tmux select-window -t $SESSION:1
elif [[ "$PROFILE" == "SGDIR" || "$PROFILE" == "sgdir" ]]
then
  exports="export PYTHONPATH=$PYTHONPATH:$HOME/Workspace/www/sgdir/releases/pepiniere-sgdir/venv/lib/python2.7/site-packages:$HOME/Workspace/www/sgdir/current/new_scripts"
  tmux select-window -t $SESSION:1
  tmux select-pane -t 2
  tmux send-keys "g mothership" C-m
  tmux select-window -t $SESSION:2
  tmux select-pane -t 0
  tmux send-keys "g sgdir && ${exports} && vis" C-m
  tmux select-pane -t 1
  tmux select-pane -t 2
elif [[ "$PROFILE" == "SGDIR-VAGRANT" || "$PROFILE" == "sgdir-vagrant" ]]
then
  exports="export PYTHONPATH=$PYTHONPATH:$HOME/Workspace/www/sgdir/releases/pepiniere-sgdir/venv/lib/python2.7/site-packages:$HOME/Workspace/www/sgdir/current/new_scripts"
  tmux select-window -t $SESSION:1
  tmux select-pane -t 2
  tmux send-keys "g mothership vagrant up" C-m
  tmux select-window -t $SESSION:2
  tmux select-pane -t 0
  tmux send-keys "g sgdir && ${exports} && vis" C-m
  tmux select-pane -t 1
  tmux send-keys "ssh -A tnuvadm@dev-mothership.pepinie.re" C-m
  tmux select-pane -t 2
  tmux send-keys "g sgdir && npm run build:dev" C-m
elif [ "$PROFILE" == "HOME" ];
then
  tmux select-pane -t 0
  tmux send-keys "echo 'HOME'" C-m
  tmux select-pane -t 2
  tmux send-keys "echo 'HOME'" C-m
  tmux select-window -t $SESSION:2
  tmux send-keys "vim --servername VI" C-m
elif [ "$PROFILE" == "GO" ];
then
  tmux select-pane -t 0
  tmux send-keys "cd $GOPATH" C-m
  tmux select-pane -t 3
  tmux send-keys "$GOPATH/bin/gotour" C-m
  tmux select-pane -t 4
  tmux send-keys "cd ~/Documents/golang/golang.org && python -m SimpleHTTPServer 4444" C-m
  tmux select-pane -t 1
  tmux send-keys "cd $GOPATH" C-m
  tmux select-pane -t 2
  tmux send-keys "echo 'GO'" C-m
  tmux select-window -t $SESSION:2
  tmux select-pane -t 0
  tmux send-keys "vim --servername VI" C-m
elif [ "$PROFILE" == "JHIPSTER" ];
then
  tmux select-pane -t 0
  tmux send-keys "cd ~/Projects/jhipster" C-m
  tmux select-pane -t 2
  tmux send-keys "docker start jhipster && sleep 5 && ssh -p 4022 jhipster@localhost -t 'cd /jhipster; bash -l'" C-m
  tmux select-window -t $SESSION:2
  tmux select-pane -t 0
  tmux send-keys "cd ~/Projects/jhipster/ && vim --servername VI" C-m
elif [ "$PROFILE" == "demo" ];
then
  tmux select-pane -t 0
  tmux send-keys "cd ~/Projects/jhipster/demo" C-m
  tmux select-pane -t 2
  tmux send-keys "cd ~/Projects/jhipster/demo && docker-compose start && sleep 5 && ssh -p 4022 jhipster@localhost -t 'cd /jhipster; mvn spring-boot:run; bash -l'" C-m
  tmux select-pane -t 3
  tmux send-keys "sleep 6 && ssh -p 4022 jhipster@localhost -t 'cd /jhipster; grunt serve; bash -l'" C-m
  tmux select-window -t $SESSION:2
  tmux select-pane -t 0
  tmux send-keys "cd ~/Projects/jhipster/demo && vim --servername VI" C-m
else
  echo "pas de profile defini"
fi

tmux select-window -t $SESSION:1
# Attach to session
tmux -2 attach-session -t $SESSION

