# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# source ~/.zplug/zplug

stty -ixon
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="candy"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

autoload -U colors
colors

export TERM=xterm-256color
export EDITOR=nvim

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
plugins=(git hub gulp npm nvm go jump docker docker-compose asdf mix kubectl)

# User configuration

export PATH=$PATH:"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export PATH=~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH
export PATH=~/.local/bin:$PATH

export KEYTIMEOUT=1

source $ZSH/oh-my-zsh.sh
fpath=(~/.zsh/completions $fpath)
autoload -U compinit && compinit
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export TNU_ROOT_DIRECTORY=~/Project/fastit/aws/
export TNU_SGDIR_ROOT_DIRECTORY=${TNU_ROOT_DIRECTORY}/sgdir/release/pepiniere-sgdir

export PATH=$PATH:~/bin
export PATH=$PATH:~/bin/clever-cloud
export PATH=$PATH:~/bin/hugo
export PATH=$PATH:~/bin/gatling/bin
export PATH=$PATH:~/bin/purescript
export PATH=$PATH:~/bin/robomongo-1.0.0-rc1/bin
export PATH=$PATH:~/bin/sonar-runner-2.4/bin
export PATH=$PATH:~/bin/caddy
export PATH=$PATH:~/Applications/mongodb/bin
export PATH=$PATH:~/bin/hub/bin
export PATH=$PATH:~/bin/VSCode
export PATH=$PATH:~/bin/arduino
export PATH=$PATH:~/bin/todolist
export PATH=$PATH:~/Applications/lci/
export PATH=$PATH:~/Applications/gitflow/bin
export PATH=$PATH:~/Applications/docker-compose
export PATH=$PATH:~/Applications/packer

export PATH=$PATH:~/.asdf/installs/elixir/1.5.1/.mix/
export PATH=$PATH:$HOME/.meteor



export GOROOT=$HOME/bin/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/Project/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.cargo/bin

alias g="jump"
alias m="bookmark"
alias d="deletemark"
alias p="showmarks"
alias vi="vis --remote "
alias vis="vim --servername VI "
alias go_watch_test='watchmedo shell-command --patterns="*.go;*.txt;*.json" --recursive --command="go test" -W .'
alias git=hub
alias dc=docker-compose
alias clever='LD_PRELOAD=libcurl.so.3 clever'


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

drbb () {
    if (( $# == 1 ))
    then
        docker run -it -u `id -u`:`id -g` --rm -v `pwd`:/appli -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group $1 /bin/bash
    else
        echo "need param for image to run"
    fi
}

source ~/.zshrc_alias
source ~/.zshrc_functions
source ~/.config/api_keys

source /etc/profile.d/snapd.sh

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[[ -s "$HOME/.cargo/env" ]] && source $HOME/.cargo/env
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[[ -s /home/nico/.rsvm/rsvm.sh ]] && . /home/nico/.rsvm/rsvm.sh # This loads RSVM

if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  . ~/.config/exercism/exercism_completion.zsh
fi

# tabtab source for jhipster package
# uninstall by removing these lines or running `tabtab uninstall jhipster`
[[ -f /home/nico/.nvm/versions/node/v6.10.2/lib/node_modules/generator-jhipster/node_modules/tabtab/.completions/jhipster.zsh ]] && . /home/nico/.nvm/versions/node/v6.10.2/lib/node_modules/generator-jhipster/node_modules/tabtab/.completions/jhipster.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/bin/sdkman"
[[ -s "$HOME/bin/sdkman/bin/sdkman-init.sh" ]] && source "$HOME/bin/sdkman/bin/sdkman-init.sh"
