# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

source ~/.zplug/zplug

stty -ixon
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="candy"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

autoload -U colors
colors

export TERM=xterm-256color

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
plugins=(git hub gulp npm nvm go)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export PATH=~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH
export PATH=~/.local/bin:$PATH

export M2_HOME=/usr/local/maven
export M2=$M2_HOME/bin
export PATH=$M2:$PATH

export KEYTIMEOUT=1

zplug "robbyrussell/oh-my-zsh", as:plugin, do:"source $ZSH/oh-my-zsh.sh"
zplug "jocelynmallon/zshmarks", as:plugin
zplug "bobthecow/git-flow-completion", as:plugin
zplug load

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

source $ZSH/oh-my-zsh.sh
source $ZPLUG_HOME/repos/bobthecow/git-flow-completion/git-flow-completion.zsh
fpath=(~/.zsh/completions $fpath)
autoload -U compinit && compinit
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias g="jump"
alias m="bookmark"
alias d="deletemark"
alias p="showmarks"
alias vi="vis --remote "
alias vis="vim --servername VI "
alias go_watch_test='watchmedo shell-command --patterns="*.go;*.txt;*.json" --recursive --command="go test" -W .'

export TNU_ROOT_DIRECTORY=~/Workspace
export TNU_SGDIR_ROOT_DIRECTORY=~/Workspace/sgdir/release/pepiniere-sgdir

export PATH=$PATH:~/Applications/mongodb/bin
export PATH=$PATH:~/Applications/hub/bin
export PATH=$PATH:~/Applications/lci/
export PATH=$PATH:~/Applications/gitflow/bin
export PATH=$PATH:~/Applications/docker-compose


export GOROOT=$HOME/Applications/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/Projects/go
export PATH=$PATH:$GOPATH/bin

export GATLING_HOME=$HOME/Applications/gatling

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

