# Path to your oh-my-zsh installation.
export ZSH=/home/nicolas/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="candy-nsa"
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

autoload -U colors
colors

export TERM=xterm-256color

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zshmarks hub gulp npm vim-mode nvm)

# User configuration

export PATH="/home/nicolas/.gvm/vertx/current/bin:/home/nicolas/.gvm/springboot/current/bin:/home/nicolas/.gvm/lazybones/current/bin:/home/nicolas/.gvm/jbake/current/bin:/home/nicolas/.gvm/groovyserv/current/bin:/home/nicolas/.gvm/groovy/current/bin:/home/nicolas/.gvm/griffon/current/bin:/home/nicolas/.gvm/grails/current/bin:/home/nicolas/.gvm/gradle/current/bin:/home/nicolas/.gvm/glide/current/bin:/home/nicolas/.gvm/gaiden/current/bin:/home/nicolas/.gvm/crash/current/bin:/home/nicolas/.gvm/asciidoctorj/current/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export M2_HOME=/usr/local/maven
export M2=$M2_HOME/bin
export PATH=$M2:$PATH


source $ZSH/oh-my-zsh.sh

fpath=(~/.zsh/completions $fpath)
autoload -U compinit && compinit
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias g="jump"
alias m="bookmark"
alias d="deletemark"
alias p="showmarks"
alias vi="vim --servername VI --remote "

export TNU_ROOT_DIRECTORY=~/Workspace
export TNU_SGDIR_ROOT_DIRECTORY=~/Workspace/sgdir/release/pepiniere-sgdir



# The next line updates PATH for the Google Cloud SDK.
source '/home/nicolas/google-cloud-sdk/path.zsh.inc'

# The next line enables bash completion for gcloud.
source '/home/nicolas/google-cloud-sdk/completion.zsh.inc'

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export PATH=$PATH:~/Applications/mongodb/bin
export PATH=$PATH:~/Applications/hub/
export PATH=$PATH:~/Applications/lci/

export GOROOT=$HOME/Applications/go1.4.2
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/Project/go

alias vimgo='vim -u ~/.vimrc.go'
export GATLING_HOME=$HOME/Applications/gatling

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "/home/nicolas/.gvm/bin/gvm-init.sh" ]] && source "/home/nicolas/.gvm/bin/gvm-init.sh"

export NVM_DIR="/home/nicolas/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm


